name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Publish Version
        required: true
        type: string
        default: 0.0.0    

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          package-manager-chache: false
          
      - name: Set package version
        run: |
          npm version "${{ inputs.version }}" --no-git-tag-version

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish

      - name: Commit version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add package.json
          git commit -m "Release v${{ inputs.version }}"
          git push

      - name: Create release notes
        run: |
          CHANGELOG="$(cat CHANGELOG.md)"
          VERSION="${{ inputs.version }}"

          cat > release-notes.md <<EOF
          $CHANGELOG

          ---
          ### :computer: Installing

          There are 3 install methods available. Pick one that suits you the best.

          **NPM**

          \`\`\`
          npm install @theblackswitch/yamp@$VERSION
          \`\`\`

          **ES module**

          \`\`\`js
          import * as YAMP from "https://cdn.jsdelivr.net/npm/@theblackswitch/yamp@$VERSION/dist/main.js"
          \`\`\`

          **HTML Script**

          \`\`\`html
          <script src="https://cdn.jsdelivr.net/npm/@theblackswitch/yamp@$VERSION/dist/main.global.js"></script>
          \`\`\`
          EOF


      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${{ inputs.version }}"

          gh release create "v$VERSION" \
            --title "v$VERSION" \
            --notes-file release-notes.md
